import { describe, expect } from "bun:test"
import { Effect, FileSystem, Layer } from "effect"
import { NodeFileSystem } from "@effect/platform-node"
import { AxeSync } from "@opencode-ai/core/axe-sync"
import { Memory } from "@opencode-ai/core/memory"
import { testEffect } from "./lib/effect"
import { tmpdir } from "./fixture/tmpdir"

const it = testEffect(
  AxeSync.layer.pipe(
    Layer.provideMerge(Memory.defaultLayer),
    Layer.provideMerge(NodeFileSystem.layer),
  ),
)

function withTmpDir<A, E, R>(body: (dir: string) => Effect.Effect<A, E, R>) {
  return Effect.acquireRelease(
    Effect.promise(() => tmpdir()),
    (tmp) => Effect.promise(() => tmp[Symbol.asyncDispose]()),
  ).pipe(Effect.flatMap((tmp) => body(tmp.path)))
}

describe("AxeSync", () => {
  it.effect("save writes entries to AXE.md", () =>
    withTmpDir((dir) =>
      Effect.gen(function* () {
        const memory = yield* Memory.Service
        const axeSync = yield* AxeSync.Service

        yield* memory.set("project-name", "openaxe")
        yield* memory.set("language", "TypeScript")
        yield* axeSync.save(dir)

        const fs = yield* FileSystem.FileSystem
        const content = yield* fs.readFileString(`${dir}/AXE.md`)
        expect(content).toContain("# AXE - Project Memory")
        expect(content).toContain("## general")
        expect(content).toContain("- **project-name**: openaxe")
        expect(content).toContain("- **language**: TypeScript")
      }),
    ),
  )

  it.effect("save groups entries by kind", () =>
    withTmpDir((dir) =>
      Effect.gen(function* () {
        const memory = yield* Memory.Service
        const axeSync = yield* AxeSync.Service

        yield* memory.set("greeting", "hello")
        yield* memory.set("instruction", "be concise")
        yield* axeSync.save(dir)

        const fs = yield* FileSystem.FileSystem
        const content = yield* fs.readFileString(`${dir}/AXE.md`)
        // Both default to "general" kind
        expect(content).toContain("## general")
        expect(content).toContain("- **greeting**: hello")
        expect(content).toContain("- **instruction**: be concise")
      }),
    ),
  )

  it.effect("load parses AXE.md and sets entries", () =>
    withTmpDir((dir) =>
      Effect.gen(function* () {
        const fs = yield* FileSystem.FileSystem
        const content = [
          "# AXE - Project Memory",
          "",
          "_Auto-generated by openaxe._",
          "",
          "## general",
          "",
          "- **project-name**: openaxe",
          "- **language**: TypeScript",
          "",
        ].join("\n")
        yield* fs.writeFileString(`${dir}/AXE.md`, content)

        const axeSync = yield* AxeSync.Service
        yield* axeSync.load(dir)

        const memory = yield* Memory.Service
        expect(yield* memory.get("project-name")).toBe("openaxe")
        expect(yield* memory.get("language")).toBe("TypeScript")
      }),
    ),
  )

  it.effect("load handles missing AXE.md gracefully", () =>
    withTmpDir((dir) =>
      Effect.gen(function* () {
        const axeSync = yield* AxeSync.Service
        yield* axeSync.load(dir)
        // No assertion needed — we just verify it doesn't throw
      }),
    ),
  )

  it.effect("save with empty store produces header-only file", () =>
    withTmpDir((dir) =>
      Effect.gen(function* () {
        const axeSync = yield* AxeSync.Service
        yield* axeSync.save(dir)

        const fs = yield* FileSystem.FileSystem
        const content = yield* fs.readFileString(`${dir}/AXE.md`)
        expect(content).toContain("# AXE - Project Memory")
        expect(content).not.toContain("##")
      }),
    ),
  )

  it.effect("save and load round-trips multiline values", () =>
    withTmpDir((dir) =>
      Effect.gen(function* () {
        const memory = yield* Memory.Service
        const axeSync = yield* AxeSync.Service

        yield* memory.set("message", "hello\nworld")
        yield* axeSync.save(dir)

        const fs = yield* FileSystem.FileSystem
        const content = yield* fs.readFileString(`${dir}/AXE.md`)
        expect(content).toContain("- **message**: hello")
        expect(content).toContain("  world")

        // Clear memory and reload
        yield* memory.remove("message")
        yield* axeSync.load(dir)
        expect(yield* memory.get("message")).toBe("hello\nworld")
      }),
    ),
  )
})
