import { performance } from "node:perf_hooks"

async function time<T>(label: string, fn: () => Promise<T>): Promise<T> {
  const t0 = performance.now()
  const result = await fn()
  console.log(`  ${label.padEnd(65)} ${(performance.now() - t0).toFixed(0)}ms`)
  return result
}

async function measure() {
  const start = performance.now()
  console.log("\n=== location-layer individual imports ===\n")

  await time(`effect`, () => import("effect"))
  await time(`@opencode-ai/core/location`, () => import("@opencode-ai/core/location"))
  await time(`@opencode-ai/core/policy`, () => import("@opencode-ai/core/policy"))
  await time(`@opencode-ai/core/config`, () => import("@opencode-ai/core/config"))
  await time(`@opencode-ai/core/plugin`, () => import("@opencode-ai/core/plugin"))
  await time(`@opencode-ai/core/catalog`, () => import("@opencode-ai/core/catalog"))
  await time(`@opencode-ai/core/integration`, () => import("@opencode-ai/core/integration"))
  await time(`@opencode-ai/core/command`, () => import("@opencode-ai/core/command"))
  await time(`@opencode-ai/core/agent`, () => import("@opencode-ai/core/agent"))
  await time(`@opencode-ai/core/plugin/internal`, () => import("@opencode-ai/core/plugin/internal"))
  await time(`@opencode-ai/core/project`, () => import("@opencode-ai/core/project"))
  await time(`@opencode-ai/core/project/copy`, () => import("@opencode-ai/core/project/copy"))
  await time(`@opencode-ai/core/event`, () => import("@opencode-ai/core/event"))
  await time(`@opencode-ai/core/credential`, () => import("@opencode-ai/core/credential"))
  await time(`@opencode-ai/core/npm`, () => import("@opencode-ai/core/npm"))
  await time(`@opencode-ai/core/models-dev`, () => import("@opencode-ai/core/models-dev"))
  await time(`@opencode-ai/core/fs-util`, () => import("@opencode-ai/core/fs-util"))
  await time(`@opencode-ai/core/git`, () => import("@opencode-ai/core/git"))
  await time(`@opencode-ai/core/global`, () => import("@opencode-ai/core/global"))
  await time(`@opencode-ai/core/database/database`, () => import("@opencode-ai/core/database/database"))
  await time(`@opencode-ai/core/permission`, () => import("@opencode-ai/core/permission"))
  await time(`@opencode-ai/core/permission/saved`, () => import("@opencode-ai/core/permission/saved"))
  await time(`@opencode-ai/core/filesystem`, () => import("@opencode-ai/core/filesystem"))
  await time(`@opencode-ai/core/ripgrep`, () => import("@opencode-ai/core/ripgrep"))
  await time(`@opencode-ai/core/filesystem/watcher`, () => import("@opencode-ai/core/filesystem/watcher"))
  await time(`@opencode-ai/core/location-mutation`, () => import("@opencode-ai/core/location-mutation"))
  await time(`@opencode-ai/core/file-mutation`, () => import("@opencode-ai/core/file-mutation"))
  await time(`@opencode-ai/core/reference`, () => import("@opencode-ai/core/reference"))
  await time(`@opencode-ai/core/reference/guidance`, () => import("@opencode-ai/core/reference/guidance"))
  await time(`@opencode-ai/core/repository-cache`, () => import("@opencode-ai/core/repository-cache"))
  await time(`@opencode-ai/core/pty`, () => import("@opencode-ai/core/pty"))
  await time(`@opencode-ai/core/skill`, () => import("@opencode-ai/core/skill"))
  await time(`@opencode-ai/core/skill/guidance`, () => import("@opencode-ai/core/skill/guidance"))
  await time(`@opencode-ai/core/tool/builtins`, () => import("@opencode-ai/core/tool/builtins"))
  await time(`@opencode-ai/core/image`, () => import("@opencode-ai/core/image"))
  await time(`@opencode-ai/core/tool/registry`, () => import("@opencode-ai/core/tool/registry"))
  await time(`@opencode-ai/core/tool/application-tools`, () => import("@opencode-ai/core/tool/application-tools"))
  await time(`@opencode-ai/core/tool-output-store`, () => import("@opencode-ai/core/tool-output-store"))
  await time(`@opencode-ai/core/process`, () => import("@opencode-ai/core/process"))
  await time(`@opencode-ai/core/session/store`, () => import("@opencode-ai/core/session/store"))
  await time(`@opencode-ai/core/session/todo`, () => import("@opencode-ai/core/session/todo"))
  await time(`@opencode-ai/core/question`, () => import("@opencode-ai/core/question"))
  await time(`@opencode-ai/llm`, () => import("@opencode-ai/llm"))
  await time(`@opencode-ai/llm/route`, () => import("@opencode-ai/llm/route"))
  await time(`@opencode-ai/core/session/runner/llm`, () => import("@opencode-ai/core/session/runner/llm"))
  await time(`@opencode-ai/core/session/runner/model`, () => import("@opencode-ai/core/session/runner/model"))
  await time(`@opencode-ai/core/system-context/builtins`, () => import("@opencode-ai/core/system-context/builtins"))
  await time(`effect/unstable/http`, () => import("effect/unstable/http"))

  console.log(`\n  ${"TOTAL".padEnd(65)} ${(performance.now() - start).toFixed(0)}ms`)
}

measure().catch(console.error)
