import { Context, Effect, FileSystem, Layer } from "effect"
import { Memory } from "./memory"

export interface Interface {
  readonly save: (basePath: string) => Effect.Effect<void>
  readonly load: (basePath: string) => Effect.Effect<void>
}

export class Service extends Context.Service<Service, Interface>()("@opencode/AxeSync") {}

interface AxeEntry {
  key: string
  value: string
  kind: string
}

function formatEntries(entries: Array<{ key: string; value: unknown; kind: string }>): string {
  const lines: string[] = [
    "# AXE - Project Memory",
    "",
    "_Auto-generated by openaxe. Manual edits are preserved on next sync._",
    "",
  ]

  const grouped = new Map<string, Array<{ key: string; value: unknown }>>()
  for (const entry of entries) {
    const group = grouped.get(entry.kind) ?? []
    group.push({ key: entry.key, value: entry.value })
    grouped.set(entry.kind, group)
  }

  for (const [kind, items] of grouped) {
    lines.push(`## ${kind}`)
    lines.push("")
    for (const item of items) {
      const valueStr = String(item.value)
      if (valueStr.includes("\n")) {
        const parts = valueStr.split("\n")
        lines.push(`- **${item.key}**: ${parts[0]}`)
        for (const part of parts.slice(1)) {
          lines.push(`  ${part}`)
        }
      } else {
        lines.push(`- **${item.key}**: ${valueStr}`)
      }
    }
    lines.push("")
  }

  return lines.join("\n")
}

function parseEntries(content: string): AxeEntry[] {
  const entries: AxeEntry[] = []
  const lines = content.split("\n")
  let currentHeading: string | undefined
  let currentContent: string[] = []

  const listItemRe = /^- \*\*([^*]+)\*\*:\s*(.*)$/
  const continuationRe = /^\s{2,}(.+)$/

  function flush() {
    if (!currentHeading) return
    const nonEmpty = currentContent.filter((l) => l.trim() !== "")
    const allListItems = nonEmpty.length > 0 && nonEmpty.every(
      (l) => listItemRe.test(l.trim()) || continuationRe.test(l),
    )

    if (allListItems) {
      let i = 0
      while (i < nonEmpty.length) {
        const line = nonEmpty[i].trim()
        const m = line.match(listItemRe)
        if (m) {
          let value = m[2]
          i++
          while (i < nonEmpty.length) {
            const nextLine = nonEmpty[i]
            const cm = nextLine.match(continuationRe)
            if (cm) {
              value += "\n" + cm[1]
              i++
            } else {
              break
            }
          }
          entries.push({ key: m[1].trim(), value: value.trim(), kind: currentHeading })
        } else {
          i++
        }
      }
    } else if (nonEmpty.length > 0) {
      const key = currentHeading
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "")
      entries.push({ key: `axe-md:${key}`, value: nonEmpty.join("\n").trim(), kind: currentHeading })
    }
  }

  for (const line of lines) {
    const headingMatch = line.match(/^##\s+(.+)$/)
    if (headingMatch) {
      flush()
      currentHeading = headingMatch[1].trim()
      currentContent = []
    } else if (currentHeading) {
      currentContent.push(line)
    }
  }

  flush()
  return entries
}

export const layer = Layer.effect(
  Service,
  Effect.gen(function* () {
    const memory = yield* Memory.Service
    const fs = yield* FileSystem.FileSystem

    const save = Effect.fn("AxeSync.save")(function* (basePath: string) {
      const entries = yield* memory.list()
      const content = formatEntries(entries)
      yield* fs.writeFileString(`${basePath}/AXE.md`, content).pipe(Effect.orDie)
    })

    const load = Effect.fn("AxeSync.load")(function* (basePath: string) {
      const filePath = `${basePath}/AXE.md`
      const exists = yield* fs.exists(filePath).pipe(Effect.orDie)
      if (!exists) return

      const content = yield* fs.readFileString(filePath).pipe(Effect.orDie)
      const parsed = parseEntries(content)
      for (const entry of parsed) {
        yield* memory.set(entry.key, entry.value, entry.kind, "project", "axe-md")
      }
    })

    return Service.of({ save, load })
  }),
)

export const defaultLayer = layer

export * as AxeSync from "./axe-sync"
