import { Context, Effect, FileSystem, Layer } from "effect"
import { Memory } from "./memory"

export interface Interface {
  readonly save: (basePath: string) => Effect.Effect<void>
  readonly load: (basePath: string) => Effect.Effect<void>
}

export class Service extends Context.Service<Service, Interface>()("@opencode/AxeSync") {}

function formatEntries(entries: Array<{ key: string; value: unknown; kind: string }>): string {
  const lines: string[] = [
    "# AXE - Project Memory",
    "",
    "_Auto-generated by openaxe. Manual edits are preserved on next sync._",
    "",
  ]

  const grouped = new Map<string, Array<{ key: string; value: unknown }>>()
  for (const entry of entries) {
    const group = grouped.get(entry.kind) ?? []
    group.push({ key: entry.key, value: entry.value })
    grouped.set(entry.kind, group)
  }

  for (const [kind, items] of grouped) {
    lines.push(`## ${kind}`)
    lines.push("")
    for (const item of items) {
      const valueStr = String(item.value)
      if (valueStr.includes("\n")) {
        const parts = valueStr.split("\n")
        lines.push(`- **${item.key}**: ${parts[0]}`)
        for (const part of parts.slice(1)) {
          lines.push(`  ${part}`)
        }
      } else {
        lines.push(`- **${item.key}**: ${valueStr}`)
      }
    }
    lines.push("")
  }

  return lines.join("\n")
}

function parseEntries(content: string): Array<{ key: string; value: string; kind: string }> {
  const entries: Array<{ key: string; value: string; kind: string }> = []
  let currentKind = "general"
  const lines = content.split("\n")

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]

    const sectionMatch = line.match(/^##\s+(.+)$/)
    if (sectionMatch) {
      currentKind = sectionMatch[1].trim()
      continue
    }

    const entryMatch = line.match(/^-\s+\*\*(.+?)\*\*:\s*(.*)$/)
    if (entryMatch) {
      const key = entryMatch[1].trim()
      let value = entryMatch[2]

      while (i + 1 < lines.length && lines[i + 1].match(/^\s{2,}/)) {
        i++
        value += "\n" + lines[i].trim()
      }

      entries.push({ key, value, kind: currentKind })
    }
  }

  return entries
}

export const layer = Layer.effect(
  Service,
  Effect.gen(function* () {
    const memory = yield* Memory.Service
    const fs = yield* FileSystem.FileSystem

    const save = Effect.fn("AxeSync.save")(function* (basePath: string) {
      const entries = yield* memory.list()
      const content = formatEntries(entries)
      yield* fs.writeFileString(`${basePath}/AXE.md`, content).pipe(Effect.orDie)
    })

    const load = Effect.fn("AxeSync.load")(function* (basePath: string) {
      const filePath = `${basePath}/AXE.md`
      const exists = yield* fs.exists(filePath).pipe(Effect.orDie)
      if (!exists) return

      const content = yield* fs.readFileString(filePath).pipe(Effect.orDie)
      const parsed = parseEntries(content)
      for (const entry of parsed) {
        yield* memory.set(entry.key, entry.value)
      }
    })

    return Service.of({ save, load })
  }),
)

export const defaultLayer = layer

export * as AxeSync from "./axe-sync"
